### ISSUE TITLE
Regression error

### ISSUE THREAD

**Issue by prinshul** [BayesWatch/deep-kernel-transfer#10]
Hi,

After following the steps mentioned in the README file for regression, I am getting the following error using spectral kernel.

python train_regression.py --method="DKT" --seed=1
[0] - Loss: nan  MSE: nan noise: nan
Traceback (most recent call last):
  File "train_regression.py", line 37, in <module>
    model.train_loop(epoch, optimizer)
  File "/deep-kernel-transfer/methods/DKT_regression.py", line 53, in train_loop
    predictions = self.model(z)
  File "/home/user/.local/lib/python3.7/site-packages/gpytorch/models/exact_gp.py", line 256, in _call_
    raise RuntimeError("You must train on the training inputs!")
RuntimeError: You must train on the training inputs!

Can you please how to correct it and get the desired results?

Also, using rbf kernel I am getting Average MSE: 0.243 +- 0.18 with the default settings on QMUL data but the reported MSE  is much lower. Is it in-range or out-range?

Thanks.

**Comment by mpatacchiola** [comment]
See answer to the same issue [here](https://github.com/BayesWatch/deep-kernel-transfer/issues/9).
